// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.12.3
// source: github.com/amazingchow/photon-dance-consistent-hashing/pb/oplog.proto

package api

import (
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type OperationType int32

const (
	OperationType_OPERATION_TYPE_ADD_SHARD    OperationType = 0
	OperationType_OPERATION_TYPE_REMOVE_SHARD OperationType = 1
	OperationType_OPERATION_TYPE_MAP_KEY      OperationType = 2
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "OPERATION_TYPE_ADD_SHARD",
		1: "OPERATION_TYPE_REMOVE_SHARD",
		2: "OPERATION_TYPE_MAP_KEY",
	}
	OperationType_value = map[string]int32{
		"OPERATION_TYPE_ADD_SHARD":    0,
		"OPERATION_TYPE_REMOVE_SHARD": 1,
		"OPERATION_TYPE_MAP_KEY":      2,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_github_com_amazingchow_photon_dance_consistent_hashing_pb_oplog_proto_enumTypes[0].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_github_com_amazingchow_photon_dance_consistent_hashing_pb_oplog_proto_enumTypes[0]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_github_com_amazingchow_photon_dance_consistent_hashing_pb_oplog_proto_rawDescGZIP(), []int{0}
}

type OpLogEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	OperationType OperationType        `protobuf:"varint,1,opt,name=operation_type,json=operationType,proto3,enum=amazingchow.photon_dance_consistent_hashing.OperationType" json:"operation_type,omitempty"`
	OperationTime *timestamp.Timestamp `protobuf:"bytes,2,opt,name=operation_time,json=operationTime,proto3" json:"operation_time,omitempty"`
	Payload       []byte               `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
}

func (x *OpLogEntry) Reset() {
	*x = OpLogEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_github_com_amazingchow_photon_dance_consistent_hashing_pb_oplog_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OpLogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OpLogEntry) ProtoMessage() {}

func (x *OpLogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_github_com_amazingchow_photon_dance_consistent_hashing_pb_oplog_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OpLogEntry.ProtoReflect.Descriptor instead.
func (*OpLogEntry) Descriptor() ([]byte, []int) {
	return file_github_com_amazingchow_photon_dance_consistent_hashing_pb_oplog_proto_rawDescGZIP(), []int{0}
}

func (x *OpLogEntry) GetOperationType() OperationType {
	if x != nil {
		return x.OperationType
	}
	return OperationType_OPERATION_TYPE_ADD_SHARD
}

func (x *OpLogEntry) GetOperationTime() *timestamp.Timestamp {
	if x != nil {
		return x.OperationTime
	}
	return nil
}

func (x *OpLogEntry) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

var File_github_com_amazingchow_photon_dance_consistent_hashing_pb_oplog_proto protoreflect.FileDescriptor

var file_github_com_amazingchow_photon_dance_consistent_hashing_pb_oplog_proto_rawDesc = []byte{
	0x0a, 0x45, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x6d, 0x61,
	0x7a, 0x69, 0x6e, 0x67, 0x63, 0x68, 0x6f, 0x77, 0x2f, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x6e, 0x2d,
	0x64, 0x61, 0x6e, 0x63, 0x65, 0x2d, 0x63, 0x6f, 0x6e, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x74,
	0x2d, 0x68, 0x61, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x6f, 0x70, 0x6c, 0x6f,
	0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x2b, 0x61, 0x6d, 0x61, 0x7a, 0x69, 0x6e, 0x67,
	0x63, 0x68, 0x6f, 0x77, 0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f, 0x6e, 0x5f, 0x64, 0x61, 0x6e, 0x63,
	0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x68, 0x61, 0x73,
	0x68, 0x69, 0x6e, 0x67, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcc, 0x01, 0x0a, 0x0a, 0x4f, 0x70, 0x4c, 0x6f, 0x67, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x12, 0x61, 0x0a, 0x0e, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x3a, 0x2e, 0x61,
	0x6d, 0x61, 0x7a, 0x69, 0x6e, 0x67, 0x63, 0x68, 0x6f, 0x77, 0x2e, 0x70, 0x68, 0x6f, 0x74, 0x6f,
	0x6e, 0x5f, 0x64, 0x61, 0x6e, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x73, 0x69, 0x73, 0x74, 0x65,
	0x6e, 0x74, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x2e, 0x4f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x41, 0x0a, 0x0e, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0d, 0x6f, 0x70, 0x65,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x61,
	0x79, 0x6c, 0x6f, 0x61, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x70, 0x61, 0x79,
	0x6c, 0x6f, 0x61, 0x64, 0x2a, 0x6a, 0x0a, 0x0d, 0x4f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x18, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49,
	0x4f, 0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x41, 0x44, 0x44, 0x5f, 0x53, 0x48, 0x41, 0x52,
	0x44, 0x10, 0x00, 0x12, 0x1f, 0x0a, 0x1b, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f, 0x4e,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x52, 0x45, 0x4d, 0x4f, 0x56, 0x45, 0x5f, 0x53, 0x48, 0x41,
	0x52, 0x44, 0x10, 0x01, 0x12, 0x1a, 0x0a, 0x16, 0x4f, 0x50, 0x45, 0x52, 0x41, 0x54, 0x49, 0x4f,
	0x4e, 0x5f, 0x54, 0x59, 0x50, 0x45, 0x5f, 0x4d, 0x41, 0x50, 0x5f, 0x4b, 0x45, 0x59, 0x10, 0x02,
	0x42, 0x3c, 0x5a, 0x3a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61,
	0x6d, 0x61, 0x7a, 0x69, 0x6e, 0x67, 0x63, 0x68, 0x6f, 0x77, 0x2f, 0x70, 0x68, 0x6f, 0x74, 0x6f,
	0x6e, 0x2d, 0x64, 0x61, 0x6e, 0x63, 0x65, 0x2d, 0x63, 0x6f, 0x6e, 0x73, 0x69, 0x73, 0x74, 0x65,
	0x6e, 0x74, 0x2d, 0x68, 0x61, 0x73, 0x68, 0x69, 0x6e, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_github_com_amazingchow_photon_dance_consistent_hashing_pb_oplog_proto_rawDescOnce sync.Once
	file_github_com_amazingchow_photon_dance_consistent_hashing_pb_oplog_proto_rawDescData = file_github_com_amazingchow_photon_dance_consistent_hashing_pb_oplog_proto_rawDesc
)

func file_github_com_amazingchow_photon_dance_consistent_hashing_pb_oplog_proto_rawDescGZIP() []byte {
	file_github_com_amazingchow_photon_dance_consistent_hashing_pb_oplog_proto_rawDescOnce.Do(func() {
		file_github_com_amazingchow_photon_dance_consistent_hashing_pb_oplog_proto_rawDescData = protoimpl.X.CompressGZIP(file_github_com_amazingchow_photon_dance_consistent_hashing_pb_oplog_proto_rawDescData)
	})
	return file_github_com_amazingchow_photon_dance_consistent_hashing_pb_oplog_proto_rawDescData
}

var file_github_com_amazingchow_photon_dance_consistent_hashing_pb_oplog_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_github_com_amazingchow_photon_dance_consistent_hashing_pb_oplog_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_github_com_amazingchow_photon_dance_consistent_hashing_pb_oplog_proto_goTypes = []interface{}{
	(OperationType)(0),          // 0: amazingchow.photon_dance_consistent_hashing.OperationType
	(*OpLogEntry)(nil),          // 1: amazingchow.photon_dance_consistent_hashing.OpLogEntry
	(*timestamp.Timestamp)(nil), // 2: google.protobuf.Timestamp
}
var file_github_com_amazingchow_photon_dance_consistent_hashing_pb_oplog_proto_depIdxs = []int32{
	0, // 0: amazingchow.photon_dance_consistent_hashing.OpLogEntry.operation_type:type_name -> amazingchow.photon_dance_consistent_hashing.OperationType
	2, // 1: amazingchow.photon_dance_consistent_hashing.OpLogEntry.operation_time:type_name -> google.protobuf.Timestamp
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_github_com_amazingchow_photon_dance_consistent_hashing_pb_oplog_proto_init() }
func file_github_com_amazingchow_photon_dance_consistent_hashing_pb_oplog_proto_init() {
	if File_github_com_amazingchow_photon_dance_consistent_hashing_pb_oplog_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_github_com_amazingchow_photon_dance_consistent_hashing_pb_oplog_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*OpLogEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_github_com_amazingchow_photon_dance_consistent_hashing_pb_oplog_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_github_com_amazingchow_photon_dance_consistent_hashing_pb_oplog_proto_goTypes,
		DependencyIndexes: file_github_com_amazingchow_photon_dance_consistent_hashing_pb_oplog_proto_depIdxs,
		EnumInfos:         file_github_com_amazingchow_photon_dance_consistent_hashing_pb_oplog_proto_enumTypes,
		MessageInfos:      file_github_com_amazingchow_photon_dance_consistent_hashing_pb_oplog_proto_msgTypes,
	}.Build()
	File_github_com_amazingchow_photon_dance_consistent_hashing_pb_oplog_proto = out.File
	file_github_com_amazingchow_photon_dance_consistent_hashing_pb_oplog_proto_rawDesc = nil
	file_github_com_amazingchow_photon_dance_consistent_hashing_pb_oplog_proto_goTypes = nil
	file_github_com_amazingchow_photon_dance_consistent_hashing_pb_oplog_proto_depIdxs = nil
}
